/**
 * Created by apach3 on 2018/2/7.
 * https://apach3q.github.io
 * wechat:VC-Lihaoooooo
 */

export const JSONVALUE = {
    "rspCode": "000000",
    "rspMsg": "操作成功",
    "data": [
        {
            "id": 7,
            "goodsName": "夏季新款女式女装 SA77212-01 005",
            "goodsPicUrl": "http://img.zcool.cn/community/016c325569800a0000004383b32bf6.jpg@1280w_1l_2o_100sh.jpg",
            "goodsPrices": 1100,
            "goodsOriginalPrices": "1500",
            "highPraiseNum": 200,
            "highPraiseProbability": "65.5",
            "sales": 21,
            "newProduct": "1",
            "clothesLength": "长款",
            "area": "北京",
            "applicablePeople": "学生",
            "activeTags": "满减",
            "storeName": "互联网垃圾分类处理",
            "brand": "品牌5",
            "getModel": "领型1",
            "inventory": 6,
            "type": null
        },
        {
            "id": 7,
            "goodsName": "夏季新款女式女装 SA77212-01 005",
            "goodsPicUrl": "http://img.zcool.cn/community/016c325569800a0000004383b32bf6.jpg@1280w_1l_2o_100sh.jpg",
            "goodsPrices": 1100,
            "goodsOriginalPrices": "1500",
            "highPraiseNum": 200,
            "highPraiseProbability": "65.5",
            "sales": 21,
            "newProduct": "1",
            "clothesLength": "长款",
            "area": "北京",
            "applicablePeople": "学生",
            "activeTags": "满减",
            "storeName": "互联网垃圾分类处理",
            "brand": "品牌5",
            "getModel": "领型1",
            "inventory": 6,
            "type": null
        },
        {
            "id": 7,
            "goodsName": "夏季新款女式女装 SA77212-01 005",
            "goodsPicUrl": "http://img.zcool.cn/community/016c325569800a0000004383b32bf6.jpg@1280w_1l_2o_100sh.jpg",
            "goodsPrices": 1100,
            "goodsOriginalPrices": "1500",
            "highPraiseNum": 200,
            "highPraiseProbability": "65.5",
            "sales": 21,
            "newProduct": "1",
            "clothesLength": "长款",
            "area": "北京",
            "applicablePeople": "学生",
            "activeTags": "满减",
            "storeName": "互联网垃圾分类处理",
            "brand": "品牌5",
            "getModel": "领型1",
            "inventory": 6,
            "type": null
        },
        {
            "id": 8,
            "goodsName": "互联网文化衫 SA77212-01 005",
            "goodsPicUrl": "http://img.zcool.cn/community/01a17855427d210000019ae9bc4daf.jpg",
            "goodsPrices": 10000,
            "goodsOriginalPrices": "10002",
            "highPraiseNum": 200,
            "highPraiseProbability": "80.9",
            "sales": 100,
            "newProduct": "0",
            "clothesLength": "常规款",
            "area": "上海",
            "applicablePeople": "学生",
            "activeTags": "分期免息",
            "storeName": "互联网后端开发部",
            "brand": "品牌5",
            "getModel": "领型5",
            "inventory": 11,
            "type": null
        },
        {
            "id": 1,
            "goodsName": "佳洁士健康专家防蛀修护牙膏长效清新薄荷1",
            "goodsPicUrl": "https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1514898655859&di=b375cfe929e49ba12b5eca1fd9feb62e&imgtype=0&src=http%3A%2F%2Fimg001.hc360.cn%2Fm7%2FM03%2F84%2F90%2FwKhQpFcYTYWEDit2AAAAAGsMrpc510.jpg",
            "goodsPrices": 10,
            "goodsOriginalPrices": "150",
            "highPraiseNum": 559,
            "highPraiseProbability": "90",
            "sales": 10000,
            "newProduct": "0",
            "clothesLength": "中长款",
            "area": "上海",
            "applicablePeople": "少女",
            "activeTags": "分期免息",
            "storeName": "互联网二手衣回收站",
            "brand": "品牌1",
            "getModel": "领型1",
            "inventory": 5,
            "type": null
        },
        {
            "id": 1,
            "goodsName": "佳洁士健康专家防蛀修护牙膏长效清新薄荷1",
            "goodsPicUrl": "https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1514898655859&di=b375cfe929e49ba12b5eca1fd9feb62e&imgtype=0&src=http%3A%2F%2Fimg001.hc360.cn%2Fm7%2FM03%2F84%2F90%2FwKhQpFcYTYWEDit2AAAAAGsMrpc510.jpg",
            "goodsPrices": 10,
            "goodsOriginalPrices": "150",
            "highPraiseNum": 559,
            "highPraiseProbability": "90",
            "sales": 10000,
            "newProduct": "0",
            "clothesLength": "中长款",
            "area": "上海",
            "applicablePeople": "少女",
            "activeTags": "分期免息",
            "storeName": "互联网二手衣回收站",
            "brand": "品牌1",
            "getModel": "领型1",
            "inventory": 5,
            "type": null
        },
        {
            "id": 9,
            "goodsName": "互联网文化衫 SA77212-01 005",
            "goodsPicUrl": "http://img.zcool.cn/community/01a17855427d210000019ae9bc4daf.jpg",
            "goodsPrices": 5000,
            "goodsOriginalPrices": "5001",
            "highPraiseNum": 200,
            "highPraiseProbability": "80.9",
            "sales": 101,
            "newProduct": "0",
            "clothesLength": "常规款",
            "area": "杭州",
            "applicablePeople": "学生",
            "activeTags": "分期免息",
            "storeName": "互联网技术产品部",
            "brand": "品牌6",
            "getModel": "领型6",
            "inventory": 15,
            "type": null
        },
        {
            "id": 9,
            "goodsName": "互联网文化衫 SA77212-01 005",
            "goodsPicUrl": "http://img.zcool.cn/community/01a17855427d210000019ae9bc4daf.jpg",
            "goodsPrices": 5000,
            "goodsOriginalPrices": "5001",
            "highPraiseNum": 200,
            "highPraiseProbability": "80.9",
            "sales": 101,
            "newProduct": "0",
            "clothesLength": "常规款",
            "area": "杭州",
            "applicablePeople": "学生",
            "activeTags": "分期免息",
            "storeName": "互联网技术产品部",
            "brand": "品牌6",
            "getModel": "领型6",
            "inventory": 15,
            "type": null
        },
        {
            "id": 9,
            "goodsName": "互联网文化衫 SA77212-01 005",
            "goodsPicUrl": "http://img.zcool.cn/community/01a17855427d210000019ae9bc4daf.jpg",
            "goodsPrices": 5000,
            "goodsOriginalPrices": "5001",
            "highPraiseNum": 200,
            "highPraiseProbability": "80.9",
            "sales": 101,
            "newProduct": "0",
            "clothesLength": "常规款",
            "area": "杭州",
            "applicablePeople": "学生",
            "activeTags": "分期免息",
            "storeName": "互联网技术产品部",
            "brand": "品牌6",
            "getModel": "领型6",
            "inventory": 15,
            "type": null
        }
    ]
};